language:
    - php

php:
    - 5.6
#    - 7.0
#    - hhvm
    
#matrix:
#  allow_failures:
#    - php: hhvm

script: 
    - sudo phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml

before_script:
    - travis_retry composer self-update
    - sudo chmod 777 /etc/bind
    - sudo chmod 666 /etc/bind/db.root
    - cp ./tests/config.travis.yml ./config.yml
    - sudo usermod -a -G root $USER
    - wget https://phar.phpunit.de/phpunit.phar
    - chmod 777 phpunit.phar
    - sudo mv phpunit.phar /usr/local/bin/phpunit
    - phpunit --version
#    - sudo echo "date.timezone = Europe/Prague" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_install:
#    - pip install --user codecov
    - sudo apt-get -qq update
    - sudo apt-get install -y bind9

after_success:
#    - codecov
