language:
    - php

php:
    - 5.6
#    - 7.0
#    - hhvm
    
#matrix:
#  allow_failures:
#    - php: hhvm

#services:
#    - bind9

script: 
    - sudo -E su $USER -c 'phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml;'

before_script:
    - travis_retry composer self-update
    - sudo chmod 777 /etc/bind
    - sudo chmod 666 /etc/bind/db.root
    - cp ./tests/config.travis.yml ./config.yml
    - sudo usermod -a -G root $USER
    - wget https://phar.phpunit.de/phpunit.phar
    - chmod 777 phpunit.phar
    - sudo mv phpunit.phar /usr/local/bin/phpunit
    - phpunit --version

before_install:
#    - pip install --user codecov
    - sudo apt-get -qq update
    - sudo apt-get install -y bind9
    - sudo apt-get install php5-xdebug

after_success:
#    - codecov
