language:
    - php

php:
    - 5.6
#    - 7.0
#    - hhvm
    
#matrix:
#  allow_failures:
#    - php: hhvm

#services:
#    - bind9

script: 
    - travis_retry phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml

before_script:
    - travis_retry composer self-update
    - travis_retry composer global require "phpunit/phpunit=5.0.*"
    - cat /etc/bind/db.root
    - cp ./tests/config.travis.yml ./config.yml

before_install:
#    - pip install --user codecov
    - sudo apt-get -qq update
    - sudo apt-get install -y bind9

after_success:
#    - codecov
