system:
    # command for stop/start/status of bind
    bind-restart: "/etc/init.d/bind9 restart"

    # SYSTEMCTL (etc. systemctl restart bind9.service)
    # use systemctl 0=false or 1=true - OPTIONAL (if true script not use 'bind-restart')
    systemctl: "1"
    # name of bind service in systemctl
    bindservice: "bind9.service"
    
    # where is file with root zones
    rzfile: "/etc/bind/db.root"

    # admin email for any warns and errors - no use in this version
    admin-email:  "name@domain.com"

# url source for db.root
source:
    url:    "ftp://ftp.rs.internic.net/domain/root.zone"

# test domain (for dig test if bind config is ok)
test:
    domain: "google.com"
    