system:
    # command for stop/start/status of bind
    bind-restart: "/etc/init.d/bind9 restart"

    # SYSTEMCTL (etc. systemctl restart bind9.service)
    # use systemctl 0=false or 1=true - OPTIONAL (if true script not use 'bind-restart')
    systemctl: "1"
    # name of bind service in systemctl
    bindservice: "bind9.service"
    
    # where is file with root zones
    rzfile: "/etc/bind/db.root"

    # bind statistics url
    # howto: https://ftp.isc.org/isc/bind9/9.10.4b2/doc/arm/Bv9ARM.ch06.html#statschannels
    statsurl: "127.0.0.1:8053/xml/v2"

# url source for db.root
source:
    url:    "ftp://ftp.rs.internic.net/domain/root.zone"

# test domain (for dig test if bind config is ok)
test:
    domain: "google.com"

# Send errors to email
mail:
    # 0=false 1=true, if true, script will be send errors to email
    sendmail: "0"
    # from:
    email-from: "from@email.tld"
    # to:
    email-to: "to@email.tld"